### ISSUE TITLE
Will this become a Nuget package?

### ISSUE THREAD

**Issue by LoganElliott** [pitermarx/NCalc2#1]
I'm looking at submitting a pull request for some small improvements with larger data calculations.  Would this repo or your NCalc-Edge have a higher chance of a newer Nuget package being release?

**Comment by pitermarx** [comment]
what do you mean by "larger data" ? 
is it a minor fix or improvement? if so use the -Edge repo. I created it to be a mirror of the original source and have only bug fixes.
it its a major change or improvement use this repo

**Comment by LoganElliott** [comment]
Basically some of the calculations I was doing which was causing int/float overflows so I swapped out the int/floats that were causing the problem to long/double. The changes are pretty minor so I'll make a pull request to -Edge.
