### ISSUE TITLE
.NET 4.6 version

### ISSUE THREAD

**Issue by ellern** [pitermarx/NCalc2#3]
Any chance you can update this to use the latest .NET 4.6?

**Comment by ellern** [comment]
I have tried but the `ExpressionMixCachePerformanceTest` jumps from <10ms to >500ms.

I don't know if that's a problem with ANTLR or the lexer or parser I generated.

**Comment by pitermarx** [comment]
Why do you need to update? Is it not possible to reference this from a .net 4.6 project?

**Comment by ellern** [comment]
Probably not, it's actually because I need to have a task based `EvaluateFunctionHandler` and `EvaluateParameterHandler` and I figured it would be best to start out with the latest antlr version.

Btw. performance seems to be on par after I removed the TRACE constant from Release builds.

**Comment by pitermarx** [comment]
Why did release builds have TRACE defined? Please remove it and create pull request.
The Task class exists on .net 4. Is it really necessary to update to 4.6 to do your custom Evaluates?

**Comment by ellern** [comment]
The trace constant was turned on by mistake. Some of my Function- and Parameter methods needs to consume async methods.

**Comment by pitermarx** [comment]
I dont think i will up the .net framework just to have an async Handler.
Feel free to fork this though.
If i find the use case really relevant  i might consider it
