### ISSUE TITLE
Allow type mismatches to resolve to "false", or provide hook to customize comparison behavior

### ISSUE THREAD

**Issue by tmenier** [pitermarx/NCalc2#4]
I'm evaluating expressions with some highly dynamic, unknown-at-runtime data. Say integer values are passed for x and y in the following expression:

`x = 5 or y = 'foo'`

Ideally, if x is 5 I'd like this to evaluate to true. But in the case where y is an integer, the entire expression fails with a `FormatException`. If y is null, it fails with a `NullReferenceException`. Both are thrown from [EvaluationVisitor.CompareUsingMostPreciseType](https://github.com/pitermarx/NCalc2/blob/master/NCalc2/Visitors/EvaluationVisitor.cs#L46).

I'm not sure if evaluating to false in those cases instead throwing exceptions is necessarily more correct. Maybe a better approach would be to provide hooks into those comparisons to allow that behavior to be customized.

Generally speaking, would you consider this project active? I searched hard for a good .NET expression parsing engine and none seem to be very active from what I've seen. (I'm actually using the original NCalc, but your forks are much newer so I figured you might be more open to further development.) If a new fork would be the way to go, or me taking over this one, I would gladly entertain the idea. Our company is investing fairly heavily in a new rules engine of which this could be an important component. I'd be glad to keep it alive and moving forward. Alternatively, if you'd consider a pull request, I could do that too.

Thanks!

**Comment by pitermarx** [comment]
This project is not stable nor finished. Its a work in progress. Not active lately...
If you need a good library for evaluating expressions use the original one. https://github.com/pitermarx/NCalc-Edge
The exceptions thrown seem correct to me. If you need the behaviour to be diferent on NCalc-Edge, you should fork the project as I wont change the original intent of the author.
Maybe in the future, when I try to evolve NCalc 2 I can provide configuration to choose if the comparison of diferent types should throw or if the null value is allowed in comparisons.
In this repo I'm open to PR's with this funcionality

**Comment by tmenier** [comment]
Thanks. Have you ever reached out to the original NCalc author? I think it's a safe bet he doesn't want to maintain it anymore. NCalc and NCalc-Edge are 2 different things from a NuGet perspective; maybe he'd allow you to take ownership of NCalc and move it forward. I thought about inquiring myself but wanted to get your thoughts on it first.

**Comment by pitermarx** [comment]
I talked to him once, when I created NCalc-Edge. He said I could take "ownership" of the project and mantain it if I wanted as long as I kept the [Copyright and License](https://github.com/pitermarx/NCalc-Edge/blob/master/LICENSE). 
The problem is that I just dont have the time to take the project anywhere.
The only thing I have tried to do is to respond to Issues on GitHub

**Comment by tmenier** [comment]
Sounds good. I appreciate the response. I think I'll start with a PR to NCalc-Edge that'll provide what I'm looking for either as a config option or via some sort of hook. I'll be sure to keep the original intent intact by default.
