### ISSUE TITLE
TraceInformation

### ISSUE THREAD

**Issue by SeanSobeySage** [pitermarx/NCalc2#5]
Hi

Is there a way to disable TraceInformation logging? We are using logging in our app and the logs are getting spammed by NCalc logs, for example Trace.TraceInformation in Expression.cs.

Thanks

**Comment by pitermarx** [comment]
You should probably use [Ncalc-Edge](https://github.com/pitermarx/NCalc-Edge). This is a prototype of a future idea to upgrade NCalc
